apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: mostafaemad96/gateway-service:v1
          ports:
            - containerPort: 5000
          env:
            - name: PRODUCTS_URL
              value: http://products:5002
            - name: USERS_URL
              value: http://users:5001
            - name: ORDERS_URL
              value: http://orders:5003
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20    
